version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hrm-postgres
    restart: always
    environment:
      POSTGRES_USER: hrm_user
      POSTGRES_PASSWORD: hrm_pass
      POSTGRES_DB: hrm_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hrm_user -d hrm_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
